# Generated by Django 5.2.4 on 2025-11-24 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('genre', models.CharField(choices=[('G', 'Garçon'), ('F', 'Fille')], max_length=1)),
                ('taille_groupe', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('G', 'Garçon'), ('F', 'Fille')], max_length=1)),
                ('universite', models.CharField(max_length=100)),
                ('cohorte', models.CharField(choices=[('1', '1ère cohorte'), ('2', '2ème cohorte'), ('3', '3ème cohorte')], max_length=1)),
                ('groupe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudiants', to='core.groupe')),
            ],
            options={
                'unique_together': {('nom', 'prenom')},
            },
        ),
    ]
